### PR TITLE
Fix NullPointerException when adding new card using Local Audio

### LINKED ISSUE #71: Local audio source not being picked for Anki card on Android
The audio on pop-up works fine, but it is not added to anki card and uses online audio and not offline local audio from ankiconnect folder. 

There is the same issue pushed on yomidevs, but no response at all sadly or any help. 
https://github.com/yomidevs/local-audio-yomichan/issues/34

I just confused what is wrong. My wifi connection is really poor and having offline set-up for mining and creating cards with audio would be nice.

I have the last version (1.14) of ankiconnect on the phone (e-ink Palma 2 reader, android 13) 

tried both mp3 version and opus version of android.db audio collection for yomitan pop-up

Would appreciate for any help!

### PR DESCRIPTION
**Pull request by Manhhao**
Fixes #71 

There are some devices, where the audio path is not fully decoded. This causes a NullPointerException [here](https://github.com/KamWithK/AnkiconnectAndroid/blob/a075592ab0b33a2ec3b849e6ac0483e1833f7c32/app/src/main/java/com/kamwithk/ankiconnectandroid/routing/LocalAudioAPIRouting.java#L226). 

Instead of `audio/20170823111828.mp3` the path remains encoded as `audio%2F20170823111828.mp3` .

The issue doesn't seem to occur on every device:
- I wasn't able to reproduce it in Android Studio on an Android 15 instance, but on my physical Android e-reader.
- At least 3 people with different devices had this issue on the TMW Discord
- A few others mentioned they didn't have this issue.

While debugging, I did notice that percents are supposed to be decoded at some point, but it seems like the code never executes with `audio%2F20170823111828.mp3` as the input. Since this issue doesn't affect everyone, and since I was reluctant to make any deeper changes due to not being familiar with the full code, I instead opted to fix it by decoding the path at the problematic place. I have confirmed that this fixes the issue for OP of #71 .

If you want to try reproducing this: 

- Set up Yomitan with a single Dict, e.g. Jitendex
- Set up the Local Audio Server, and make sure it is the only audio source in Yomitan
- Completely disable internet access on device/emulator
- Try creating a new card

Since AnkiConnect fails to retrieve the audio files due to the path still being encoded, and since Yomitan is unable to fall back to an internet source, the audio field is left blank.
It would also be good to mention that this only happens when creating a new card, playing audio works fine without internet, and the path during execution of playback is also properly decoded.
If you'd like to, you can check out the e-reader thread in novel-discussion on TMW.

### CODE REVIEW

File: app/src/main/java/com/kamwithk/ankiconnectandroid/routing/LocalAudioAPIRouting.java [hunk 1]
```diff
@@ -223,7 +225,16 @@ public NanoHTTPD.Response getAudioHandleError(String source, String path) {
...
         EntriesDatabase db = getDB();
         AudioFileEntryDao audioFileEntryDao = db.audioFileEntryDao();
-        byte[] data = audioFileEntryDao.getData(path, source);
+
+        String pathDecoded;
+        try {
+            pathDecoded = URLDecoder.decode(path, "UTF-8");
+        }
+        catch (UnsupportedEncodingException e) {
+            pathDecoded = path;
```
Comment (KamWithK) [inline app/src/main/java/com/kamwithk/ankiconnectandroid/routing/LocalAudioAPIRouting.java:234]: Do we actually trigger this? If so this shouldn't work?

Comment (Manhhao) [reply app/src/main/java/com/kamwithk/ankiconnectandroid/routing/LocalAudioAPIRouting.java:234]: No, the catch block is never triggered, this only throws if "UTF-8" was an invalid encoding, which it is obviously not. I had to surround it with a try-catch block since you'd have to add the exception to the method signature if you were to only do `pathDecoded = URLDecoder.decode(path, "UTF-8");`, which would cause other stuff to break. Not adding anything to the catch block would theoretically suffice, but since I am not initializing pathDecoded in the line above, I just iniatilized it to path there so it doesn't complain. I replaced path with pathDecoded in the line below the snipped so pathDecoded is used afterwards.

**Comment by KamWithK** [comment]
Thank you for contributing @Manhhao!
I have merged the PR

**Comment by Manhhao** [comment]
No Problem! If I ever find the time I‘ll poke around and see if I am able to fix it properly, but it‘s good to get a fix out since there are quite a few who were affected.
